version: "3.9"
services:
  server:
    build: ./ServerControler
    ports:
      - "25565:25565" #Default minecraft server port
      - "4567:4567" #Default SparkJava port
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - db
    depends_on:
      - flyway
  flyway:
    image: dhoer/flyway:alpine
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd migrate
    volumes:
      - ./sql_versions:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
volumes:
  logvolume01: {}
